version: '3.9'
services:

  ### cAdvisor
  cadvisor:
    #https://hub.docker.com/r/google/cadvisor/
    image: google/cadvisor:latest
    restart: always
    container_name: cadvisor
    privileged: true
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    ports:
      - 8080:8080

  ### Prometheus
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: always
    command:
      - '--web.enable-lifecycle'
      - '--config.file=/etc/prometheus/prometheus.yml'
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    # depends_on:
    #   - cadvisor
    ports:
      - 9090:9090

  ### Alertmanager
  alertmanager:
    image: prom/alertmanager
    container_name: alertmanager
    user: root
    ports: 
      - 9093:9093
    volumes:
      - ~/prometheus/alertmanager/config/:/etc/alertmanager/
    networks:
      - promnet
    restart: always
    command:
      - '--config.file=/etc/alertmanager/alertmanager.yml'



  ### Grafana
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    environment:
      # - GF_PATHS_CONFIG=/config_files/grafana.ini
      - GF_SECURITY_ADMIN_USER=myadmin
      - GF_SECURITY_ADMIN_PASSWORD=myadmin
      - GF_SERVER_DOMAIN=localhost
      - GF_SERVER_HTTP_PORT=3000
    privileged: true
    volumes:
      - ./grafana/config_files:/config_files
      - ./grafana/data:/var/lib/grafana
    links:
      - prometheus:prometheus
    ports:
    - 3000:3000


  ### node-exporter
  node-exporter:
    image: prom/node-exporter:latest
    container_name: node_exporter
    restart: unless-stopped
    expose:
      - 9100
    ports:
      - 9100:9100