version: '3.9'
services:

  ### cAdvisor
  cadvisor:
    #https://hub.docker.com/r/google/cadvisor/
    image: google/cadvisor:latest
    restart: unless-stopped
    container_name: cadvisor
    privileged: true
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    ports:
      - 8080:8080

  ### Prometheus
  prometheus:
    image: prom/prometheus:latest
    restart: unless-stopped
    container_name: prometheus
    user: root
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus/data:/prometheus
    # depends_on:
    #   - cadvisor
    ports:
      - 9090:9090

  ### Alertmanager
  alertmanager:
    image: prom/alertmanager
    container_name: alertmanager
    user: root
    ports: 
      - 9093:9093
    volumes:
      - ~/prometheus/alertmanager/config/:/etc/alertmanager/
    networks:
      - promnet
    restart: always
    command:
      - '--config.file=/etc/alertmanager/alertmanager.yml'



  ### Grafana
  grafana:
    image: grafana/grafana:latest
    restart: unless-stopped
    container_name: grafana
    environment:
      # - GF_PATHS_CONFIG=/config_files/grafana.ini
      - GF_SECURITY_ADMIN_USER=myadmin
      - GF_SECURITY_ADMIN_PASSWORD=myadmin
      - GF_SERVER_DOMAIN=localhost
      - GF_SERVER_HTTP_PORT=3000
    privileged: true
    volumes:
      - ./grafana/config_files:/config_files
      - ./grafana/data:/var/lib/grafana
    links:
      - prometheus:prometheus
    ports:
    - 3000:3000



  ### Node-exporter
  node-exporter:
    image: prom/node-exporter:latest
    restart: unless-stopped
    container_name: node-exporter
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--path.rootfs=/rootfs'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
      - '--collector.textfile.directory=/node_exporter/prom'
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    ports:
      - 9100:9100